### PR TITLE
Added 4k resoulution (3840 x 2160) Support

### PR DESCRIPTION
**Pull request by ChristianBDev**
This changed the CSS for 4k Monitors and added more spice to the hud.

Made more end-user friendly

### CODE REVIEW

**Comment by ChristianBDev** [comment]
May need to be built again

**Comment by MonkeyWhisper** [comment]
"added more spice to the hud."

Outline specifically what has been changed and pictures. 

Also, do not send PR if the source is not built

**Comment by ChristianBDev** [comment]
> "added more spice to the hud."
> 
> Outline specifically what has been changed and pictures.
> 
> Also, do not send PR if the source is not built

I go to build the resource but then takes it back to recent commit, so I am confused on the building process as to why my changes dont stay after being built

**Comment by MonkeyWhisper** [comment]
Okay, reopen PR when you got it all resolved

**Pull request closed without merging**
